version: '3.8'

services:
  whisper-timestamped:
    container_name: whisper-timestamped
    ports:
      - "8888:8888"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input/:/app/input
      - ./cache:/app/cache
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    command: ["gunicorn", "transcribe:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8888", "--timeout", "1800"]
